config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:create]
  resources :posts, except: [:destroy] do
    collection do
      get 'my'
    end
  end
  devise_for :users
  root 'posts#index'
end

app/models/comment.rb
# Comment Model
class Comment < ActiveRecord::Base
  belongs_to :author, foreign_key: 'user_id', class_name: User
  belongs_to :post

  validates :author, presence: true
  validates :post, presence: true
  validates :body, presence: true

  scope :latest, -> { order('created_at desc') }
end

app/models/post.rb
# Post Model
class Post < ActiveRecord::Base
  belongs_to :author, foreign_key: 'user_id', class_name: User
  has_many :comments

  validates :author, presence: true
  validates :title, presence: true
  validates :body, presence: true

  scope :latest, -> { order('created_at desc') }

  paginates_per 5
  max_paginates_per 50
end

app/models/user.rb
# User Model
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments

  def display_name
    return email if first_name.blank? && last_name.blank?
    return first_name if last_name.blank?
    return last_name if first_name.blank?
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
# Application Controller - base controller for application
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :about_me])
  end
end

app/controllers/comments_controller.rb
# Comments Controller - handles actions relating to Comments on Posts
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      redirect_to @comment.post, notice: 'Comment was successfully created.'
    else
      @post = @comment.post
      render 'posts/show'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:post_id, :body)
  end
end

app/controllers/posts_controller.rb
# Posts Controller - actions relating to creating, editing, and displaying posts
class PostsController < ApplicationController
  before_action :set_post, only: [:show]
  before_action :set_post_from_current_user_pool, only: [:edit, :update]
  before_action :authenticate_user!, only: [:my, :new, :create, :edit, :update]

  def index
    @posts = Post.latest.page params[:page]
  end

  def my
    @posts = current_user.posts.latest.page params[:page]
  end

  def show
    @comment = Comment.new(post_id: @post.id)
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def set_post_from_current_user_pool
    # intentionally raising a 404 if you request a post from another user
    @post = current_user.posts.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
# Application Helper
module ApplicationHelper
  def published_date(d)
    d.strftime('%b %e, %Y')
  end
end

app/views/comments/_form.html.haml
= form_for(comment) do |f|
  - if comment.errors.any?
    #error_explanation
      %h2
        = pluralize(comment.errors.count, "error")
        prohibited this comment from being saved:
      %ul
        - comment.errors.full_messages.each do |message|
          %li= message
  .form-group
    = f.label :body, 'Enter your comment:'
    <br>
    = f.text_area :body, autofocus: true, class: 'form-control'
  .actions
    = f.hidden_field :post_id
    = f.submit 'Submit Comment', class: 'btn btn-success'
    %button#cancel_new_comment.btn.btn-danger Cancel

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Openblog
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    %link{rel: 'stylesheet', href: 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css', integrity: 'sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u', crossorigin: 'anonymous'}
    %link{rel: 'stylesheet', href: 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css', integrity: 'sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp', crossorigin: 'anonymous'}
    %script{src: 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js', integrity: 'sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa', crossorigin: 'anonymous'}
    = csrf_meta_tags

  %body
    #page_container.container-fluid
      .row
        .col-sm-3
          %h1.site_name Open Blog
        .col-sm-9.pull-right.nav= render 'shared/nav'
        .col-xs-12
          - if notice
            %p.notice.alert.alert-success= notice
          - if alert
            %p.alert.alert-danger= alert
          = yield

app/views/posts/_form.html.haml
= form_for(post) do |f|
  - if post.errors.any?
    #error_explanation
      %h2
        = pluralize(post.errors.count, "error")
        prohibited this post from being saved:
      %ul
        - post.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.label :title
    %br/
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :body
    %br/
    = f.text_area :body, rows: 10, class: 'form-control'
  .actions
    = f.submit 'Submit', class: 'btn btn-success'

app/views/posts/edit.html.haml
%h2.underlined.page_heading Edit Post

= render 'form', post: @post

app/views/posts/index.html.haml
%h2.underlined.page_heading All Posts
= link_to 'New Post', new_post_path, class: 'btn btn-success pull-right'
- if @posts.count > 0
  %table.table.table-striped#all_posts
    %thead
      %tr
        %th Post
        %th Author
        %th Date
        %th Comments
    %tbody
      - @posts.each do |post|
        %tr
          %td
            %strong= link_to post.title, post_path(post.id)
          %td= post.author.display_name
          %td= published_date(post.created_at)
          %td= post.comments.count
  = paginate @posts
- else
  %p
    %em There are currently no posts.

app/views/posts/my.html.haml
%h2.underlined.page_heading My Posts
= link_to 'New Post', new_post_path, class: 'btn btn-success pull-right'
- if @posts.count > 0
  %table.table.table-striped
    %thead
      %tr
        %th Post
        %th Date
        %th Comments
        %th Edit
    %tbody
      - @posts.each do |post|
        %tr
          %td
            %strong= link_to post.title, post_path(post.id)
          %td= published_date(post.created_at)
          %td= post.comments.count
          %td= link_to 'edit', edit_post_path(post.id)
  = paginate @posts
- else
  %p
    %em You haven't written any posts.
    = link_to 'Write one now!', new_post_path

app/views/posts/new.html.haml
%h2.underlined.page_heading New Post

= render 'form', post: @post

app/views/posts/show.html.haml
#post
  %h2.underlined.page_heading.post_title= @post.title
  %h3.byline= "by #{@post.author.display_name}"
  %h4.publish_date= published_date(@post.created_at)
  %p= raw h(@post.body).gsub(/\n/, '<br/>')

  #new_comment_form.hidden
    = render 'comments/form', comment: @comment

  %h3.underlined Comments

  %button#new_comment.btn.btn-success.pull-right Add a Comment

  - if @post.comments.count > 0
    - @post.comments.latest.each do |comment|
      %p{id: "comment_#{comment.id}"}
        = raw h(comment.body).gsub(/\n/, '<br/>')
        %br/
        %strong= "- #{comment.author.display_name}"
        %br/
        = published_date(comment.created_at)
  - else
    %p
      %em There are currently no comments!

  - if @comment.errors.count > 0
    :javascript
      $(document).ready( function() {
        $('div#new_comment_form').removeClass('hidden');
        $('html, body').animate({
          scrollTop: $("div#new_comment_form").offset().top
        }, 200);
      });

  :javascript
    $(document).ready( function() {
      $('button#new_comment').click(function(event) {
        event.preventDefault();
        $('div#new_comment_form').removeClass('hidden');
        $('button#new_comment').addClass('hidden');
      });
      $('button#cancel_new_comment').click(function(event) {
        event.preventDefault();
        $('div#new_comment_form').addClass('hidden');
        $('button#new_comment').removeClass('hidden');
      });
    
    });

app/views/shared/_nav.html.haml
= link_to 'All Posts', posts_path
- if current_user
  = link_to 'My Posts', my_posts_path
  = link_to 'Edit Profile', edit_registration_path(:user)
  = link_to "Log Out #{current_user.display_name}", destroy_user_session_path, method: :delete
- else
  = link_to "Log In", new_session_path(:user)
  = link_to "Sign Up", new_registration_path(:user)